services:
  backend:
    build: 
      context: ./backend
    container_name: osint_backend
    ports:
      - "8000:8000"
    volumes:
      # Geliştirme için backend kodları
      - ./backend:/app
      # Veritabanının kalıcı olacağı ana dizindeki data klasörü
      - ./data:/data
      # Logların tutulacağı ana dizindeki logs klasörü
      - ./logs:/logs
    environment:
      - DATABASE_URL=sqlite:////data/osint_crawler.db
      - LOG_DIR=/logs
    env_file:
      - ./backend/.env